server:
  port: 8081
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8

## redis 配置
spring:
  redis:
    host: localhost  
    port: 6379    
    timeout: 60000
    database: 0 
    pool: 
      max-active: -1     # 连接池最大连接数（使用负值表示没有限制）
      max-wait:   -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle:   8      # 连接池中的最大空闲连接
      min-idle:   0      # 连接池中的最小空闲连接
      max-total:  200
      holed: 2000
      
## Mysql 配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/miaosha
    username: root
    password: 111111
##  Mysql 分页魔板引擎
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
      
## Mybatis 配置
mybatis:
  mapperLocations: classpath*:/Mappers/*.xml
  typeAliasesPackage: com.answern.seckill.core   #entity扫描的包名
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: countSql
  
# LOGGING  
logging:  
  level:  
    com.answern.seckill.core: DEBUG 
    
debug: false
 
